/** The verdict as a standalone document, and as a PDF.
 *
 *  Printed by the browser rather than rendered again on the server. A server-side
 *  PDF means a second renderer with its own layout, its own fonts and its own
 *  idea of what a finding looks like, and the two drift — usually in the
 *  direction of the PDF quietly losing whatever was added last. Since the thing
 *  most likely to be added last is a caveat, that drift is not cosmetic. One
 *  renderer, one layout, and the print stylesheet decides what a page break may
 *  fall between.
 *
 *  What this page guarantees
 *  -------------------------
 *  A verdict that leaves this building carries its limits with it. The
 *  screenshot of a number without its caveats is the exact failure this product
 *  exists to prevent, and a PDF is a screenshot that looks official. So "what
 *  this does not say" is part of the document, not an appendix, and the print
 *  rules refuse to break a finding across a page or orphan the section heading
 *  from what follows it.
 *
 *  The header carries provenance — which dataset, which benchmark, how many
 *  scenes, which arms ran, when it was generated — because a page that ends up
 *  in somebody's slide deck six weeks from now has to be able to say what it is
 *  without the person who made it standing next to it.
 */

import { Link, useParams } from "react-router-dom";
import { useSubmission } from "../api/client";
import { Verdict } from "../components/Verdict";
import { ErrorNote, Skeleton, bytes } from "../components/ui";

function when(iso: string): string {
  if (!iso) return "";
  return new Date(iso).toISOString().replace("T", " ").slice(0, 16) + " UTC";
}

export function VerdictPage() {
  const { id } = useParams();
  const { data, isPending, error } = useSubmission(id);

  if (isPending) {
    return (
      <div className="page">
        <div className="card">
          <Skeleton rows={5} />
        </div>
      </div>
    );
  }
  if (error) {
    return (
      <div className="page">
        <ErrorNote error={error} />
      </div>
    );
  }
  if (!data) return null;

  const gate = data.gates.find((g) => g.key === "g3");
  const detail = gate?.detail ?? {};
  const arms = (detail.arms as string[] | undefined) ?? [];
  const scenes =
    (detail.ladder as { arms: Record<string, { n?: number }> }[] | undefined)?.[0]?.arms?.[
      arms[0] ?? ""
    ]?.n ?? 0;

  if (!gate || (gate.status !== "passed" && gate.status !== "abstained")) {
    return (
      <div className="page">
        <div className="note warn">
          <b>There is no verdict for this submission yet.</b>
          <div style={{ marginTop: 4 }}>
            The robot test has not produced a result, so there is nothing here to export.{" "}
            <Link to={`/submissions/${id}`}>Back to the submission</Link>.
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="page doc">
      <div className="doc-actions no-print">
        <Link className="btn" to={`/submissions/${id}`}>
          Back to the submission
        </Link>
        <span className="spacer" />
        <button type="button" className="btn primary" onClick={() => window.print()}>
          Save as PDF
        </button>
      </div>

      <header className="doc-head">
        <div className="doc-brand">
          Gantry <span className="tag">BENCH</span>
        </div>
        <h1>{data.name}</h1>
        <div className="doc-meta">
          <span>
            <b>Benchmark</b> {data.benchmark?.name} · {data.benchmark?.simulator}
          </span>
          <span>
            <b>Dataset</b> v{data.dataset?.version} ·{" "}
            {data.dataset ? bytes(data.dataset.bytes) : "—"} ·{" "}
            {data.dataset?.detected?.episodes ?? "—"} clips
          </span>
          <span>
            <b>Scenes</b> {scenes} per arm
          </span>
          <span>
            <b>Arms</b> {arms.join(", ") || "—"}
          </span>
          <span>
            <b>Run</b> {when(gate.finished_at)}
          </span>
        </div>
      </header>

      <Verdict gate={gate} />

      <footer className="doc-foot">
        Every rate on this page shows how many scenes it came from, with a 95% interval, and
        every comparison is paired on the scenes both arms ran. Rows marked “not comparable” are
        rungs one arm never measured. That is a missing measurement, not a score of zero.
        Generated by Gantry Bench for {data.benchmark?.name}. Submission{" "}
        <span className="mono">{data.id}</span>.
      </footer>
    </div>
  );
}
